### PR TITLE
Run CI on PR, not just push

### PR DESCRIPTION
**Pull request by jonathanpallant**

### CODE REVIEW

**Comment by jonathanpallant** [comment]
Failing on MSRV (1.41). Looks like an issue with https://docs.rs/fixed/1.9.0/fixed/

**Review by therealprof — APPROVED** [review]
LGTM

**Comment by jonathanpallant** [comment]
Did we expect the 1.41 MSRV build to fail?

**Comment by jonathanpallant** [comment]
Talking on Matrix, the HAL has no MSRV so this repo shouldn't either.

**Pull request merged**
